/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as IndexRouteImport } from './routes/index'

const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/despesas': typeof DespesasRoute
  '/funcionarios': typeof FuncionariosRoute
  '/lojas': typeof LojasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/despesas': typeof DespesasRoute
  '/funcionarios': typeof FuncionariosRoute
  '/lojas': typeof LojasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/despesas': typeof DespesasRoute
  '/funcionarios': typeof FuncionariosRoute
  '/lojas': typeof LojasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/despesas' | '/funcionarios' | '/lojas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/despesas' | '/funcionarios' | '/lojas'
  id: '__root__' | '/' | '/despesas' | '/funcionarios' | '/lojas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DespesasRoute: typeof DespesasRoute
  FuncionariosRoute: typeof FuncionariosRoute
  LojasRoute: typeof LojasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DespesasRoute: DespesasRoute,
  FuncionariosRoute: FuncionariosRoute,
  LojasRoute: LojasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
