/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedCargosRouteImport } from './routes/_authenticated/cargos'
import { Route as AuthenticatedComparativoRouteImport } from './routes/_authenticated/comparativo'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedContrachequeRouteImport } from './routes/_authenticated/contracheque'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedDreRouteImport } from './routes/_authenticated/dre'
import { Route as AuthenticatedFaltasRhRouteImport } from './routes/_authenticated/faltas-rh'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'
import { Route as AuthenticatedImpostosRouteImport } from './routes/_authenticated/impostos'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedLojasRouteImport } from './routes/_authenticated/lojas'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedPrestadoresRouteImport } from './routes/_authenticated/prestadores'
import { Route as AuthenticatedRescisaoRouteImport } from './routes/_authenticated/rescisao'
import { Route as AuthenticatedTitulosRouteImport } from './routes/_authenticated/titulos'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as ApiPublicHooksSyncDriveRouteImport } from './routes/api/public/hooks/sync-drive'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCargosRoute = AuthenticatedCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComparativoRoute =
  AuthenticatedComparativoRouteImport.update({
    id: '/comparativo',
    path: '/comparativo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContrachequeRoute =
  AuthenticatedContrachequeRouteImport.update({
    id: '/contracheque',
    path: '/contracheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDreRoute = AuthenticatedDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaltasRhRoute = AuthenticatedFaltasRhRouteImport.update({
  id: '/faltas-rh',
  path: '/faltas-rh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariosRoute =
  AuthenticatedFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpostosRoute = AuthenticatedImpostosRouteImport.update({
  id: '/impostos',
  path: '/impostos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLojasRoute = AuthenticatedLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrestadoresRoute =
  AuthenticatedPrestadoresRouteImport.update({
    id: '/prestadores',
    path: '/prestadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRescisaoRoute = AuthenticatedRescisaoRouteImport.update({
  id: '/rescisao',
  path: '/rescisao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTitulosRoute = AuthenticatedTitulosRouteImport.update({
  id: '/titulos',
  path: '/titulos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksSyncDriveRoute = ApiPublicHooksSyncDriveRouteImport.update({
  id: '/api/public/hooks/sync-drive',
  path: '/api/public/hooks/sync-drive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/comparativo': typeof AuthenticatedComparativoRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/contracheque': typeof AuthenticatedContrachequeRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/dre': typeof AuthenticatedDreRoute
  '/faltas-rh': typeof AuthenticatedFaltasRhRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/impostos': typeof AuthenticatedImpostosRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/lojas': typeof AuthenticatedLojasRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/prestadores': typeof AuthenticatedPrestadoresRoute
  '/rescisao': typeof AuthenticatedRescisaoRoute
  '/titulos': typeof AuthenticatedTitulosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/api/public/hooks/sync-drive': typeof ApiPublicHooksSyncDriveRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/comparativo': typeof AuthenticatedComparativoRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/contracheque': typeof AuthenticatedContrachequeRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/dre': typeof AuthenticatedDreRoute
  '/faltas-rh': typeof AuthenticatedFaltasRhRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/impostos': typeof AuthenticatedImpostosRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/lojas': typeof AuthenticatedLojasRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/prestadores': typeof AuthenticatedPrestadoresRoute
  '/rescisao': typeof AuthenticatedRescisaoRoute
  '/titulos': typeof AuthenticatedTitulosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/sync-drive': typeof ApiPublicHooksSyncDriveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/cargos': typeof AuthenticatedCargosRoute
  '/_authenticated/comparativo': typeof AuthenticatedComparativoRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/contracheque': typeof AuthenticatedContrachequeRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/dre': typeof AuthenticatedDreRoute
  '/_authenticated/faltas-rh': typeof AuthenticatedFaltasRhRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/impostos': typeof AuthenticatedImpostosRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/lojas': typeof AuthenticatedLojasRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/prestadores': typeof AuthenticatedPrestadoresRoute
  '/_authenticated/rescisao': typeof AuthenticatedRescisaoRoute
  '/_authenticated/titulos': typeof AuthenticatedTitulosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/sync-drive': typeof ApiPublicHooksSyncDriveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auditoria'
    | '/caixa'
    | '/cargos'
    | '/comparativo'
    | '/compras'
    | '/conciliacao'
    | '/contracheque'
    | '/despesas'
    | '/dre'
    | '/faltas-rh'
    | '/funcionarios'
    | '/impostos'
    | '/indicadores'
    | '/lojas'
    | '/metas'
    | '/prestadores'
    | '/rescisao'
    | '/titulos'
    | '/usuarios'
    | '/vendas'
    | '/api/public/hooks/sync-drive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auditoria'
    | '/caixa'
    | '/cargos'
    | '/comparativo'
    | '/compras'
    | '/conciliacao'
    | '/contracheque'
    | '/despesas'
    | '/dre'
    | '/faltas-rh'
    | '/funcionarios'
    | '/impostos'
    | '/indicadores'
    | '/lojas'
    | '/metas'
    | '/prestadores'
    | '/rescisao'
    | '/titulos'
    | '/usuarios'
    | '/vendas'
    | '/'
    | '/api/public/hooks/sync-drive'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/auditoria'
    | '/_authenticated/caixa'
    | '/_authenticated/cargos'
    | '/_authenticated/comparativo'
    | '/_authenticated/compras'
    | '/_authenticated/conciliacao'
    | '/_authenticated/contracheque'
    | '/_authenticated/despesas'
    | '/_authenticated/dre'
    | '/_authenticated/faltas-rh'
    | '/_authenticated/funcionarios'
    | '/_authenticated/impostos'
    | '/_authenticated/indicadores'
    | '/_authenticated/lojas'
    | '/_authenticated/metas'
    | '/_authenticated/prestadores'
    | '/_authenticated/rescisao'
    | '/_authenticated/titulos'
    | '/_authenticated/usuarios'
    | '/_authenticated/vendas'
    | '/_authenticated/'
    | '/api/public/hooks/sync-drive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSyncDriveRoute: typeof ApiPublicHooksSyncDriveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cargos': {
      id: '/_authenticated/cargos'
      path: '/cargos'
      fullPath: '/cargos'
      preLoaderRoute: typeof AuthenticatedCargosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparativo': {
      id: '/_authenticated/comparativo'
      path: '/comparativo'
      fullPath: '/comparativo'
      preLoaderRoute: typeof AuthenticatedComparativoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracheque': {
      id: '/_authenticated/contracheque'
      path: '/contracheque'
      fullPath: '/contracheque'
      preLoaderRoute: typeof AuthenticatedContrachequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dre': {
      id: '/_authenticated/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof AuthenticatedDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faltas-rh': {
      id: '/_authenticated/faltas-rh'
      path: '/faltas-rh'
      fullPath: '/faltas-rh'
      preLoaderRoute: typeof AuthenticatedFaltasRhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios': {
      id: '/_authenticated/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AuthenticatedFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostos': {
      id: '/_authenticated/impostos'
      path: '/impostos'
      fullPath: '/impostos'
      preLoaderRoute: typeof AuthenticatedImpostosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lojas': {
      id: '/_authenticated/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof AuthenticatedLojasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prestadores': {
      id: '/_authenticated/prestadores'
      path: '/prestadores'
      fullPath: '/prestadores'
      preLoaderRoute: typeof AuthenticatedPrestadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rescisao': {
      id: '/_authenticated/rescisao'
      path: '/rescisao'
      fullPath: '/rescisao'
      preLoaderRoute: typeof AuthenticatedRescisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/titulos': {
      id: '/_authenticated/titulos'
      path: '/titulos'
      fullPath: '/titulos'
      preLoaderRoute: typeof AuthenticatedTitulosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/sync-drive': {
      id: '/api/public/hooks/sync-drive'
      path: '/api/public/hooks/sync-drive'
      fullPath: '/api/public/hooks/sync-drive'
      preLoaderRoute: typeof ApiPublicHooksSyncDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCargosRoute: typeof AuthenticatedCargosRoute
  AuthenticatedComparativoRoute: typeof AuthenticatedComparativoRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedContrachequeRoute: typeof AuthenticatedContrachequeRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedDreRoute: typeof AuthenticatedDreRoute
  AuthenticatedFaltasRhRoute: typeof AuthenticatedFaltasRhRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedImpostosRoute: typeof AuthenticatedImpostosRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedLojasRoute: typeof AuthenticatedLojasRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedPrestadoresRoute: typeof AuthenticatedPrestadoresRoute
  AuthenticatedRescisaoRoute: typeof AuthenticatedRescisaoRoute
  AuthenticatedTitulosRoute: typeof AuthenticatedTitulosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCargosRoute: AuthenticatedCargosRoute,
  AuthenticatedComparativoRoute: AuthenticatedComparativoRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedContrachequeRoute: AuthenticatedContrachequeRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedDreRoute: AuthenticatedDreRoute,
  AuthenticatedFaltasRhRoute: AuthenticatedFaltasRhRoute,
  AuthenticatedFuncionariosRoute: AuthenticatedFuncionariosRoute,
  AuthenticatedImpostosRoute: AuthenticatedImpostosRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedLojasRoute: AuthenticatedLojasRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedPrestadoresRoute: AuthenticatedPrestadoresRoute,
  AuthenticatedRescisaoRoute: AuthenticatedRescisaoRoute,
  AuthenticatedTitulosRoute: AuthenticatedTitulosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSyncDriveRoute: ApiPublicHooksSyncDriveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
