/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedLojasRouteImport } from './routes/_authenticated/lojas'
import { Route as AuthenticatedImpostosRouteImport } from './routes/_authenticated/impostos'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'
import { Route as AuthenticatedDreRouteImport } from './routes/_authenticated/dre'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedComparativoRouteImport } from './routes/_authenticated/comparativo'
import { Route as AuthenticatedCalculadoraRouteImport } from './routes/_authenticated/calculadora'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojasRoute = AuthenticatedLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpostosRoute = AuthenticatedImpostosRouteImport.update({
  id: '/impostos',
  path: '/impostos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariosRoute =
  AuthenticatedFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDreRoute = AuthenticatedDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComparativoRoute =
  AuthenticatedComparativoRouteImport.update({
    id: '/comparativo',
    path: '/comparativo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalculadoraRoute =
  AuthenticatedCalculadoraRouteImport.update({
    id: '/calculadora',
    path: '/calculadora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/calculadora': typeof AuthenticatedCalculadoraRoute
  '/comparativo': typeof AuthenticatedComparativoRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/dre': typeof AuthenticatedDreRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/impostos': typeof AuthenticatedImpostosRoute
  '/lojas': typeof AuthenticatedLojasRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/calculadora': typeof AuthenticatedCalculadoraRoute
  '/comparativo': typeof AuthenticatedComparativoRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/dre': typeof AuthenticatedDreRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/impostos': typeof AuthenticatedImpostosRoute
  '/lojas': typeof AuthenticatedLojasRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/calculadora': typeof AuthenticatedCalculadoraRoute
  '/_authenticated/comparativo': typeof AuthenticatedComparativoRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/dre': typeof AuthenticatedDreRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/impostos': typeof AuthenticatedImpostosRoute
  '/_authenticated/lojas': typeof AuthenticatedLojasRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/caixa'
    | '/calculadora'
    | '/comparativo'
    | '/despesas'
    | '/dre'
    | '/funcionarios'
    | '/impostos'
    | '/lojas'
    | '/metas'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/caixa'
    | '/calculadora'
    | '/comparativo'
    | '/despesas'
    | '/dre'
    | '/funcionarios'
    | '/impostos'
    | '/lojas'
    | '/metas'
    | '/usuarios'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/caixa'
    | '/_authenticated/calculadora'
    | '/_authenticated/comparativo'
    | '/_authenticated/despesas'
    | '/_authenticated/dre'
    | '/_authenticated/funcionarios'
    | '/_authenticated/impostos'
    | '/_authenticated/lojas'
    | '/_authenticated/metas'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lojas': {
      id: '/_authenticated/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof AuthenticatedLojasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostos': {
      id: '/_authenticated/impostos'
      path: '/impostos'
      fullPath: '/impostos'
      preLoaderRoute: typeof AuthenticatedImpostosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios': {
      id: '/_authenticated/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AuthenticatedFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dre': {
      id: '/_authenticated/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof AuthenticatedDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparativo': {
      id: '/_authenticated/comparativo'
      path: '/comparativo'
      fullPath: '/comparativo'
      preLoaderRoute: typeof AuthenticatedComparativoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculadora': {
      id: '/_authenticated/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof AuthenticatedCalculadoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCalculadoraRoute: typeof AuthenticatedCalculadoraRoute
  AuthenticatedComparativoRoute: typeof AuthenticatedComparativoRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedDreRoute: typeof AuthenticatedDreRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedImpostosRoute: typeof AuthenticatedImpostosRoute
  AuthenticatedLojasRoute: typeof AuthenticatedLojasRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCalculadoraRoute: AuthenticatedCalculadoraRoute,
  AuthenticatedComparativoRoute: AuthenticatedComparativoRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedDreRoute: AuthenticatedDreRoute,
  AuthenticatedFuncionariosRoute: AuthenticatedFuncionariosRoute,
  AuthenticatedImpostosRoute: AuthenticatedImpostosRoute,
  AuthenticatedLojasRoute: AuthenticatedLojasRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
